### ISSUE TITLE
JS get API = error 400 from localhost

### ISSUE THREAD

**Issue by KORandi** [teamrevlo/RevloAPI#1]
Hello, for some reason i can't recieve data. It ends with error: 
Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost' is therefore not allowed access. The response had HTTP status code 400.

**Comment by scottnguyen** [comment]
Need more information. What request was sent? Where did you send the request from? How do I reproduce this?

**Comment by KORandi** [comment]
Probably I got it. After adding x-api-key to the head the JS changes my GET request to OPTIONS automatically . 

> What request was sent?
```
OPTIONS /1/redemptions?page=1&refunded=false HTTP/1.1
Host: api.revlo.co
Connection: keep-alive
Cache-Control: max-age=0
Access-Control-Request-Method: GET
Origin: http://localhost
User-Agent: Mozilla/5.0 (Windows NT 6.3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36
Access-Control-Request-Headers: x-api-key
Accept: */*
DNT: 1
Referer: http://localhost/cass/
Accept-Encoding: gzip, deflate, sdch, br
Accept-Language: cs-CZ,cs;q=0.8,en;q=0.6

```
> Where did you send the request from?

From web browser, here is my JS:

```
var data = null;

var xhr = new XMLHttpRequest();
xhr.withCredentials = true;

xhr.addEventListener("readystatechange", function () {
  if (this.readyState === 4) {
    console.log(this.responseText);
  }
});

xhr.open("GET", "https://api.revlo.co/1/redemptions?page=1&refunded=false");
xhr.setRequestHeader("x-api-key", "****"); //here I put my api key

xhr.send(data);

```

Is here any solution for OPTION request?

**Comment by scottnguyen** [comment]
This is a service-wide bug. For now, you can only hit the service via backend. I'll be looking into it.

**Comment by KORandi** [comment]
Thank you, that have helped me to solve the problem.  (now I send requests via backend)

**Comment by KORandi** [comment]
Hi i found something, might be interesting for you guys.

**Cross-Site HTTP Requests**
Requests for data from a different server (than the requesting page), are called cross-site HTTP requests.

Cross-site requests are common on the web. Many pages load CSS, images, and scripts from different servers.

In modern browsers, cross-site HTTP requests from scripts are restricted to same site for security reasons.

The following line, in our PHP examples, has been added to allow cross-site access.

`header("Access-Control-Allow-Origin: *");`

source: http://www.w3schools.com/angular/angular_sql.asp

**Comment by scottnguyen** [comment]
Yeah, I found a resolution in the API backend service. It should be out soon. :)

**Comment by scottnguyen** [comment]
this was resolved service-side. closing.
