### ISSUE TITLE
Question: Testing In Browser

### ISSUE THREAD

**Issue by dinosaw** [teamrevlo/RevloAPI#4]
Hi there. Thanks for putting out an API for this! I was curious though how I could go about testing these API calls in my browser instead of requiring a terminal/console. 

I assumed it might be something like this:
`https://api.revlo.co/1/rewards?page=1&api_key=APIKEYHERE`

But that doesn't seem to work. Nor just `key=`. Any help would be greatly appreciated!

**Comment by scottnguyen** [comment]
Something like this should work:

```javascript
$.ajax({
    url: "https://api.revlo.co/1/rewards",
    headers: {'x-api-key': 'MY_API_KEY'}
  }).done(function(result){
    console.log(result);
  });
```

**Comment by dinosaw** [comment]
Heyo! Thanks for that but I meant something more in the form of a URL like the Twitch API (by appending your oauth token / key depending on the request). The reason being is because bots like Nightbot has the `urlfetch` variable and AnkhBot has the `$readapi` feature. So for example it would need to be in the format of a simple URL. If it's not possible that's fine, I was just curious if it was possible then how exactly would I go about doing it. Thanks!

**Comment by scottnguyen** [comment]
It's not possible since our auth protocol only looks for the api key in the header and not the payload.
