### ISSUE TITLE
/fans/{username}/points/bonus compare-and-set

### ISSUE THREAD

**Issue by NaomiAmethyst** [teamrevlo/RevloAPI#5]
This is a feature request to add an option to the `/fans/{username}/points/bonus` API to allow basic compare-and-set functionality.  Ideally, it would allow API integrations to get transactionality with optimistic locking:

```python
committed = False
while not committed:
  try:
    points = get_points(username) # GET /fans/{username}/points
    new_points = calculate_new_points(points) # Do whatever we want to calculate the new points
    delta = new_points - points
    points_bonus(username, { amount: delta, if_current_points: points }) # Applies bonus only if current points is equal, otherwise returns error
    committed = True
  except:
    continue
```

**Comment by scottnguyen** [comment]
Hey @Cobi, OCC would be pretty nice to have, but I don't think we can fit that into our product timeline anytime soon. As we scale out, we might need to add Lamport clocks or something internally. If that becomes the case, then I'm sure we would gladly open that up to you guys.
