### ISSUE TITLE
Redemptions UserInfo SongURL

### ISSUE THREAD

**Issue by M0nkeyRage** [teamrevlo/RevloAPI#6]
The documentation says that the UserInfo of the Redemption will have the song as "song", the name of the element in the JSON seems to be "Song URL (Youtube or Soundcloud)" is this the correct name I should use?

**Comment by scottnguyen** [comment]
Hey @M0nkeyRage, if you're using the default SongRequest template, then it's usually `song`, however, you can change that to whatever you'd like since it's an `input_field` parameter.
